### ISSUE TITLE
Upgrading/Solution file

### ISSUE THREAD

**Issue by unitrix0** [trksyln/TGMacro#9]
I've just discovered your tool and wanted to contribute. But looking at the I noticed there is no solution file (maybe on purpose?) and it's in .NET Framework 4.5.1 which is not supported anymore. Do you have any plans to upgrade?

**Comment by trksyln** [comment]
Hello, 
I didn't think it's necessary to put solution file because there is no specific changes in it. 
If you open the csproj file in visual studio, it should generate a solution file and it should work fine. 
After that you should be upgrade it up to Net Framework 4.8.1 without any code changes.

I didn't abandon the project i just stopped sharing the source code because after it got populer i found some web sites building their own with malicious code and publish it with same name and ruining it's reputation.
